### ISSUE TITLE
cuda error

### ISSUE THREAD

**Issue by flyphoenix456** [HwangBo94/Anti-UAV410#25]
Thank you so much for your work, and your open source code. I executed "python tracking_train_demo.py" according to your latest Readme, and the following CUDA error occurred. I would like to ask if you have encountered this situation. Is this situation caused by a version mismatch between cuda, pytorch, mmvc, etc. I hope you can provide the corresponding cuda version and mmcv version.
missing keys in source state_dict: rpn_head.rpn_conv.weight, rpn_head.rpn_conv.bias, rpn_head.rpn_cls.weight, rpn_head.rpn_cls.bias, rpn_head.rpn_reg.weight, rpn_head.rpn_reg.bias, roi_head.bbox_head.fc_cls.weight, roi_head.bbox_head.fc_cls.bias, roi_head.bbox_head.fc_reg.weight, roi_head.bbox_head.fc_reg.bias, roi_head.bbox_head.shared_fcs.0.weight, roi_head.bbox_head.shared_fcs.0.bias, roi_head.bbox_head.shared_fcs.1.weight, roi_head.bbox_head.shared_fcs.1.bias, rpn_similarity_learning.proj_query.0.weight, rpn_similarity_learning.proj_query.0.bias, rpn_similarity_learning.proj_query.1.weight, rpn_similarity_learning.proj_query.1.bias, rpn_similarity_learning.proj_query.2.weight, rpn_similarity_learning.proj_query.2.bias, rpn_similarity_learning.proj_query.3.weight, rpn_similarity_learning.proj_query.3.bias, rpn_similarity_learning.proj_query.4.weight, rpn_similarity_learning.proj_query.4.bias, rpn_similarity_learning.proj_out.0.weight, rpn_similarity_learning.proj_out.0.bias, rpn_similarity_learning.proj_out.1.weight, rpn_similarity_learning.proj_out.1.bias, rpn_similarity_learning.proj_out.2.weight, rpn_similarity_learning.proj_out.2.bias, rpn_similarity_learning.proj_out.3.weight, rpn_similarity_learning.proj_out.3.bias, rpn_similarity_learning.proj_out.4.weight, rpn_similarity_learning.proj_out.4.bias, rcnn_similarity_learning.proj_z.weight, rcnn_similarity_learning.proj_z.bias, rcnn_similarity_learning.proj_x.weight, rcnn_similarity_learning.proj_x.bias, rcnn_similarity_learning.proj_out.weight, rcnn_similarity_learning.proj_out.bias

2024-12-30 20:15:14,632 - mmdet - INFO - Start running, host: user16@user-SYS-4028GR-TR, work_dir: /data1/user16/Anti-UAV410/trackers/SiamDT/work_dirs/siamdt_swin_tiny_sgd
2024-12-30 20:15:14,632 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [80,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [81,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [82,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [83,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [84,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [85,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [86,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [87,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [88,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [89,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [90,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [91,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [92,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [93,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [94,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [96,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [97,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [98,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [99,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [100,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [101,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [102,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [103,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [104,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [105,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [106,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [107,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [108,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [109,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [110,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [111,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [112,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [113,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [114,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [115,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [116,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [117,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [118,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [119,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [120,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [121,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [122,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [123,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [124,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "tracking_train_demo.py", line 238, in <module>
    main()
  File "tracking_train_demo.py", line 233, in main
    meta=meta)
  File "libs/swintransformer/mmdet/apis/train.py", line 185, in train_detector
    runner.run(data_loaders, cfg.workflow)#截止此未出错
  File "/data1/user16/miniconda3/envs/SiamDT/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/data1/user16/miniconda3/envs/SiamDT/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/data1/user16/miniconda3/envs/SiamDT/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/data1/user16/miniconda3/envs/SiamDT/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "libs/swintransformer/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data) #todo 这一步计算的时候出错
  File "/data1/user16/miniconda3/envs/SiamDT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data1/user16/miniconda3/envs/SiamDT/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/data1/user16/Anti-UAV410/trackers/SiamDT/trackers/siamdt_rcnn.py", line 56, in forward
    img_z, img_x, img_meta_z, img_meta_x, **kwargs)
  File "/data1/user16/Anti-UAV410/trackers/SiamDT/trackers/siamdt_rcnn.py", line 113, in forward_train
    rpn_losses = self.rpn_head.loss(*rpn_loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "libs/swintransformer/mmdet/models/dense_heads/rpn_head.py", line 78, in loss
    gt_bboxes_ignore=gt_bboxes_ignore)
  File "/data1/user16/miniconda3/envs/SiamDT/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 189, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "libs/swintransformer/mmdet/models/dense_heads/anchor_head.py", line 467, in loss
    label_channels=label_channels)
  File "libs/swintransformer/mmdet/models/dense_heads/anchor_head.py", line 349, in get_targets
    unmap_outputs=unmap_outputs)
  File "libs/swintransformer/mmdet/core/utils/misc.py", line 29, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "libs/swintransformer/mmdet/models/dense_heads/anchor_head.py", line 226, in _get_targets_single
    gt_bboxes)
  File "libs/swintransformer/mmdet/core/bbox/samplers/base_sampler.py", line 97, in sample
    neg_inds = neg_inds.unique()
  File "/data1/user16/miniconda3/envs/SiamDT/lib/python3.7/site-packages/torch/tensor.py", line 511, in unique
    return torch.unique(self, sorted=sorted, return_inverse=return_inverse, return_counts=return_counts, dim=dim)
  File "/data1/user16/miniconda3/envs/SiamDT/lib/python3.7/site-packages/torch/_jit_internal.py", line 365, in fn
    return if_false(*args, **kwargs)
  File "/data1/user16/miniconda3/envs/SiamDT/lib/python3.7/site-packages/torch/_jit_internal.py", line 365, in fn
    return if_false(*args, **kwargs)
  File "/data1/user16/miniconda3/envs/SiamDT/lib/python3.7/site-packages/torch/functional.py", line 831, in _return_output
    output, _, _ = _unique_impl(input, sorted, return_inverse, return_counts, dim)
  File "/data1/user16/miniconda3/envs/SiamDT/lib/python3.7/site-packages/torch/functional.py", line 749, in _unique_impl
    return_counts=return_counts,
RuntimeError: transform: failed to synchronize: cudaErrorAssert: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:733 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f0f214dd2f2 in /data1/user16/miniconda3/envs/SiamDT/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f0f214da67b in /data1/user16/miniconda3/envs/SiamDT/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x809 (0x7f0f217351f9 in /data1/user16/miniconda3/envs/SiamDT/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x54 (0x7f0f214c53a4 in /data1/user16/miniconda3/envs/SiamDT/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x6ea43a (0x7f0f952f243a in /data1/user16/miniconda3/envs/SiamDT/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x6ea4e1 (0x7f0f952f24e1 in /data1/user16/miniconda3/envs/SiamDT/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #24: __libc_start_main + 0xe7 (0x7f0f97be0c87 in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by promotesd** [comment]
I also encountered this problem. Have u solved it?

**Comment by kilitezh** [comment]
I also encountered this problem. Could you please tell me how you solved it?

**Comment by promotesd** [comment]
> [@promotesd](https://github.com/promotesd) [@flyphoenix456](https://github.com/flyphoenix456) The problem is due to the version of PyTorch. It can be solved after upgrading the PyTorch version. Please refer to this [NVIDIA/thrust#1401 (comment)](https://github.com/NVIDIA/thrust/issues/1401#issuecomment-806403746)问题是由于 PyTorch 的版本造成的。升级 PyTorch 版本后即可解决。请参考这里 [NVIDIA/thrust#1401 (comment)](https://github.com/NVIDIA/thrust/issues/1401#issuecomment-806403746) `pip uninstall torch torchvision` `pip install torch===1.9.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html` `pip install torchvision===0.10.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html`
> 
> `pip uninstall mmcv-full mmdet``pip 卸载 mmcv-full mmdet` `mim install mmcv-full==1.3.17 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.1/index.html`
> 
> Hope it helps you.  希望它对您有所帮助。

Thank you！
